version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8200:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes: [./html:/var/www/html]
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes: [./db:/var/lib/mysql]
    ports:
      - 3306:3306
volumes:
   db:
