name: My-GitHubActions-Basics
env:
  APPLICATION_NAME    : "MyWordpress"
  DEPLOY_PACKAGE_NAME : "Wordpress-deploy-ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - master

jobs:
  my_ci:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
    
    - name: Execure few commands
      run : |
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Appication name: ${{ env.APPLICATION_NAME }}"
    
    - name: List current folder
      run : ls -la
   
    - name: Git clone my repo
      uses: actions/checkout@v1   
  
    - name: Create Zip deployment package
      run : |
           ls -la
           pause
           zip -r ${{ env. DEPLOY_PACKAGE_NAME }} ./ -x *.git*
           ls -la
           ping 10.0.2.7
  my_cd:
    runs-on: ubuntu-latest
    needs: [my_ci]
    env:
      VAR1 : "This is Job Level Variable1"
      VAR2 : "This is Job Level Variable2"
    
    steps:
    - name: Print Hello Message in Deploy Job
      run : echo "Hello World from Deploy job"
      
    - name: Print env vars
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is Super local Environment variable"

    
    - name: Printing Deployment package
      run : echo "Deploy pakcage name is ${{ env.DEPLOY_PACKAGE_NAME }}"
    
    - name: Lets test some packages if they are here 1
      run : ls -la

    - name: Lets test some packages if they are here 2
      run : docker ps -a
