name: My-GitHubActions-Basics
env:
  APPLICATION_NAME    : "MyWordpress"
  DEPLOY_PACKAGE_NAME : "Wordpress-deploy-ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - master

jobs:
  my_ci:
    runs-on: test

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
    
    - name: Execure few commands
      run : |
        echo "Hello Message"
        echo "Appication name: ${{ env.APPLICATION_NAME }}"
    
    - name: List current folder
      run : pwd
   
    - name: Git clone my repo
      uses: actions/checkout@v1   
  
    - name: Create Zip deployment package
      run : |
           zip -r ${{ env. DEPLOY_PACKAGE_NAME }} ./ -x *.git*
           ls -la
           pwd
           scp -r ${{ env. DEPLOY_PACKAGE_NAME }}.zip  belhard@10.0.2.10:/home/belhard/wordpress
        
  my_cd:
    runs-on: test
    needs: [my_ci]
#    if: github == 'refs/heads/master' && github.event_name == 'push' 
       
    steps:        
    - name: Printing Deployment package
      run : echo "Deploy pakcage name is ${{ env.DEPLOY_PACKAGE_NAME }}"
    
    - name: Deploy to server :)
      run : |
           echo token=${{ env.TOKEN }}
           pwd
           ssh -p 22 belhard@10.0.2.10 'cd /home/belhard/wordpress; docker stop $(docker ps -aq) && docker rm $(docker ps -aq) && docker rmi $(docker images -q) -f && docker system prune -f; unzip -o ${{ env. DEPLOY_PACKAGE_NAME }}.zip; rm ${{ env. DEPLOY_PACKAGE_NAME }}.zip; docker-compose up -d'
           curl -X POST https://api.telegram.org/bot${{ env.TOKEN }}/sendMessage -d "chat_id=1108837141" -d text="Deploy successful"
